package booking.hibernate.entities;
// Generated 23 mai 2013 11:06:21 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Artiste generated by hbm2java
 */
public class Artiste  implements java.io.Serializable {


     private Integer idArt;
     private Mobilite mobilite;
     private CategorieArt categorieArt;
     private String libNom;
     private String libPrenom;
     private BigDecimal numTarifJour;
     private String libDescr;
     private String libEmail;
     private String numMobile;
     private String libPhoto;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Artiste() {
    }

    public Artiste(Mobilite mobilite, CategorieArt categorieArt, String libNom, String libPrenom, BigDecimal numTarifJour, String libDescr, String libEmail, String numMobile, String libPhoto, Set<Reservation> reservations) {
       this.mobilite = mobilite;
       this.categorieArt = categorieArt;
       this.libNom = libNom;
       this.libPrenom = libPrenom;
       this.numTarifJour = numTarifJour;
       this.libDescr = libDescr;
       this.libEmail = libEmail;
       this.numMobile = numMobile;
       this.libPhoto = libPhoto;
       this.reservations = reservations;
    }
   
    public Integer getIdArt() {
        return this.idArt;
    }
    
    public void setIdArt(Integer idArt) {
        this.idArt = idArt;
    }
    public Mobilite getMobilite() {
        return this.mobilite;
    }
    
    public void setMobilite(Mobilite mobilite) {
        this.mobilite = mobilite;
    }
    public CategorieArt getCategorieArt() {
        return this.categorieArt;
    }
    
    public void setCategorieArt(CategorieArt categorieArt) {
        this.categorieArt = categorieArt;
    }
    public String getLibNom() {
        return this.libNom;
    }
    
    public void setLibNom(String libNom) {
        this.libNom = libNom;
    }
    public String getLibPrenom() {
        return this.libPrenom;
    }
    
    public void setLibPrenom(String libPrenom) {
        this.libPrenom = libPrenom;
    }
    public BigDecimal getNumTarifJour() {
        return this.numTarifJour;
    }
    
    public void setNumTarifJour(BigDecimal numTarifJour) {
        this.numTarifJour = numTarifJour;
    }
    public String getLibDescr() {
        return this.libDescr;
    }
    
    public void setLibDescr(String libDescr) {
        this.libDescr = libDescr;
    }
    public String getLibEmail() {
        return this.libEmail;
    }
    
    public void setLibEmail(String libEmail) {
        this.libEmail = libEmail;
    }
    public String getNumMobile() {
        return this.numMobile;
    }
    
    public void setNumMobile(String numMobile) {
        this.numMobile = numMobile;
    }
    public String getLibPhoto() {
        return this.libPhoto;
    }
    
    public void setLibPhoto(String libPhoto) {
        this.libPhoto = libPhoto;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


