package booking.hibernate.entities;
// Generated 23 mai 2013 12:27:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CategorieArt generated by hbm2java
 */
public class CategorieArt  implements java.io.Serializable {


     private int idCatg;
     private String libCatg;
     private Set<Artiste> artistes = new HashSet<Artiste>(0);

    public CategorieArt() {
    }

	
    public CategorieArt(int idCatg) {
        this.idCatg = idCatg;
    }
    public CategorieArt(int idCatg, String libCatg, Set<Artiste> artistes) {
       this.idCatg = idCatg;
       this.libCatg = libCatg;
       this.artistes = artistes;
    }
   
    public int getIdCatg() {
        return this.idCatg;
    }
    
    public void setIdCatg(int idCatg) {
        this.idCatg = idCatg;
    }
    public String getLibCatg() {
        return this.libCatg;
    }
    
    public void setLibCatg(String libCatg) {
        this.libCatg = libCatg;
    }
    public Set<Artiste> getArtistes() {
        return this.artistes;
    }
    
    public void setArtistes(Set<Artiste> artistes) {
        this.artistes = artistes;
    }




}


