package booking.hibernate.entities;
// Generated 23 mai 2013 12:27:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mobilite generated by hbm2java
 */
public class Mobilite  implements java.io.Serializable {


     private int idMobilite;
     private String libMobilite;
     private Set<Artiste> artistes = new HashSet<Artiste>(0);

    public Mobilite() {
    }

	
    public Mobilite(int idMobilite) {
        this.idMobilite = idMobilite;
    }
    public Mobilite(int idMobilite, String libMobilite, Set<Artiste> artistes) {
       this.idMobilite = idMobilite;
       this.libMobilite = libMobilite;
       this.artistes = artistes;
    }
   
    public int getIdMobilite() {
        return this.idMobilite;
    }
    
    public void setIdMobilite(int idMobilite) {
        this.idMobilite = idMobilite;
    }
    public String getLibMobilite() {
        return this.libMobilite;
    }
    
    public void setLibMobilite(String libMobilite) {
        this.libMobilite = libMobilite;
    }
    public Set<Artiste> getArtistes() {
        return this.artistes;
    }
    
    public void setArtistes(Set<Artiste> artistes) {
        this.artistes = artistes;
    }




}


