package booking.hibernate.entities;
// Generated 23 mai 2013 10:41:49 by Hibernate Tools 3.2.1.GA



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private Artiste artiste;
     private String libTheme;
     private String libLieu;
     private String indStatut;

    public Reservation() {
    }

	
    public Reservation(ReservationId id, Artiste artiste, String libTheme) {
        this.id = id;
        this.artiste = artiste;
        this.libTheme = libTheme;
    }
    public Reservation(ReservationId id, Artiste artiste, String libTheme, String libLieu, String indStatut) {
       this.id = id;
       this.artiste = artiste;
       this.libTheme = libTheme;
       this.libLieu = libLieu;
       this.indStatut = indStatut;
    }
   
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    public Artiste getArtiste() {
        return this.artiste;
    }
    
    public void setArtiste(Artiste artiste) {
        this.artiste = artiste;
    }
    public String getLibTheme() {
        return this.libTheme;
    }
    
    public void setLibTheme(String libTheme) {
        this.libTheme = libTheme;
    }
    public String getLibLieu() {
        return this.libLieu;
    }
    
    public void setLibLieu(String libLieu) {
        this.libLieu = libLieu;
    }
    public String getIndStatut() {
        return this.indStatut;
    }
    
    public void setIndStatut(String indStatut) {
        this.indStatut = indStatut;
    }




}


