package booking.hibernate.entities;
// Generated 23 mai 2013 12:34:30 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ReservationId generated by hbm2java
 */
public class ReservationId  implements java.io.Serializable {


     private int idArt;
     private Date dtEvt;

    public ReservationId() {
    }

    public ReservationId(int idArt, Date dtEvt) {
       this.idArt = idArt;
       this.dtEvt = dtEvt;
    }
   
    public int getIdArt() {
        return this.idArt;
    }
    
    public void setIdArt(int idArt) {
        this.idArt = idArt;
    }
    public Date getDtEvt() {
        return this.dtEvt;
    }
    
    public void setDtEvt(Date dtEvt) {
        this.dtEvt = dtEvt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservationId) ) return false;
		 ReservationId castOther = ( ReservationId ) other; 
         
		 return (this.getIdArt()==castOther.getIdArt())
 && ( (this.getDtEvt()==castOther.getDtEvt()) || ( this.getDtEvt()!=null && castOther.getDtEvt()!=null && this.getDtEvt().equals(castOther.getDtEvt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdArt();
         result = 37 * result + ( getDtEvt() == null ? 0 : this.getDtEvt().hashCode() );
         return result;
   }   


}


