package booking.hibernate.entities;
// Generated 23 mai 2013 10:41:49 by Hibernate Tools 3.2.1.GA



/**
 * StatutResa generated by hbm2java
 */
public class StatutResa  implements java.io.Serializable {


     private String indStatut;
     private String libStatut;

    public StatutResa() {
    }

	
    public StatutResa(String indStatut) {
        this.indStatut = indStatut;
    }
    public StatutResa(String indStatut, String libStatut) {
       this.indStatut = indStatut;
       this.libStatut = libStatut;
    }
   
    public String getIndStatut() {
        return this.indStatut;
    }
    
    public void setIndStatut(String indStatut) {
        this.indStatut = indStatut;
    }
    public String getLibStatut() {
        return this.libStatut;
    }
    
    public void setLibStatut(String libStatut) {
        this.libStatut = libStatut;
    }




}


