package booking.hibernate.entities;
// Generated 23 mai 2013 12:34:30 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * StatutResa generated by hbm2java
 */
public class StatutResa  implements java.io.Serializable {


     private String indStatut;
     private String libStatut;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public StatutResa() {
    }

	
    public StatutResa(String indStatut) {
        this.indStatut = indStatut;
    }
    public StatutResa(String indStatut, String libStatut, Set<Reservation> reservations) {
       this.indStatut = indStatut;
       this.libStatut = libStatut;
       this.reservations = reservations;
    }
   
    public String getIndStatut() {
        return this.indStatut;
    }
    
    public void setIndStatut(String indStatut) {
        this.indStatut = indStatut;
    }
    public String getLibStatut() {
        return this.libStatut;
    }
    
    public void setLibStatut(String libStatut) {
        this.libStatut = libStatut;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


