package booking.hibernate.dao;
// Generated 22 mai 2013 16:38:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CategorieArt generated by hbm2java
 */
public class CategorieArt  implements java.io.Serializable {


     private int idCatg;
     private String libCatg;
     private Set artistes = new HashSet(0);

    public CategorieArt() {
    }

	
    public CategorieArt(int idCatg) {
        this.idCatg = idCatg;
    }
    public CategorieArt(int idCatg, String libCatg, Set artistes) {
       this.idCatg = idCatg;
       this.libCatg = libCatg;
       this.artistes = artistes;
    }
   
    public int getIdCatg() {
        return this.idCatg;
    }
    
    public void setIdCatg(int idCatg) {
        this.idCatg = idCatg;
    }
    public String getLibCatg() {
        return this.libCatg;
    }
    
    public void setLibCatg(String libCatg) {
        this.libCatg = libCatg;
    }
    public Set getArtistes() {
        return this.artistes;
    }
    
    public void setArtistes(Set artistes) {
        this.artistes = artistes;
    }




}


