package booking.hibernate.dao;
// Generated 22 mai 2013 16:38:27 by Hibernate Tools 3.2.1.GA



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private String libTheme;
     private String libLieu;

    public Reservation() {
    }

	
    public Reservation(ReservationId id, String libTheme) {
        this.id = id;
        this.libTheme = libTheme;
    }
    public Reservation(ReservationId id, String libTheme, String libLieu) {
       this.id = id;
       this.libTheme = libTheme;
       this.libLieu = libLieu;
    }
   
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    public String getLibTheme() {
        return this.libTheme;
    }
    
    public void setLibTheme(String libTheme) {
        this.libTheme = libTheme;
    }
    public String getLibLieu() {
        return this.libLieu;
    }
    
    public void setLibLieu(String libLieu) {
        this.libLieu = libLieu;
    }




}


