package booking.hibernate.entity;
// Generated 22 mai 2013 14:13:06 by Hibernate Tools 3.2.1.GA



/**
 * CategorieArt generated by hbm2java
 */
public class CategorieArt  implements java.io.Serializable {


     private int idCatg;
     private String libCatg;

    public CategorieArt() {
    }

	
    public CategorieArt(int idCatg) {
        this.idCatg = idCatg;
    }
    public CategorieArt(int idCatg, String libCatg) {
       this.idCatg = idCatg;
       this.libCatg = libCatg;
    }
   
    public int getIdCatg() {
        return this.idCatg;
    }
    
    public void setIdCatg(int idCatg) {
        this.idCatg = idCatg;
    }
    public String getLibCatg() {
        return this.libCatg;
    }
    
    public void setLibCatg(String libCatg) {
        this.libCatg = libCatg;
    }




}


