package booking.hibernate.entity;
// Generated 22 mai 2013 14:13:06 by Hibernate Tools 3.2.1.GA



/**
 * Mobilite generated by hbm2java
 */
public class Mobilite  implements java.io.Serializable {


     private int idMobilite;
     private String libMobilite;

    public Mobilite() {
    }

	
    public Mobilite(int idMobilite) {
        this.idMobilite = idMobilite;
    }
    public Mobilite(int idMobilite, String libMobilite) {
       this.idMobilite = idMobilite;
       this.libMobilite = libMobilite;
    }
   
    public int getIdMobilite() {
        return this.idMobilite;
    }
    
    public void setIdMobilite(int idMobilite) {
        this.idMobilite = idMobilite;
    }
    public String getLibMobilite() {
        return this.libMobilite;
    }
    
    public void setLibMobilite(String libMobilite) {
        this.libMobilite = libMobilite;
    }




}


