package booking.hibernate.entity;
// Generated 22 mai 2013 14:13:06 by Hibernate Tools 3.2.1.GA



/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private String login;
     private String pwd;
     private String email;
     private String mobile;

    public Utilisateur() {
    }

	
    public Utilisateur(String login, String mobile) {
        this.login = login;
        this.mobile = mobile;
    }
    public Utilisateur(String login, String pwd, String email, String mobile) {
       this.login = login;
       this.pwd = pwd;
       this.email = email;
       this.mobile = mobile;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


